osx_image: xcode9.2
language: objective-c
cache:
  cocoapods: true
  bundler: true
  directories:
    - /home/travis/.rvm/
podfile: Example/Podfile
gemfile: Example/Gemfile
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_471017eff382_key -iv $encrypted_471017eff382_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - sh ssh.sh
  - gem install bundler --no-rdoc --no-ri --no-document --quiet
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version
  - bundle install --gemfile=Example/Gemfile
  - bundle exec pod install --project-directory=Example
script:
  - set -o pipefail
  - bundle exec fastlane scan
  - bundle exec fastlane lib_lint
  - bundle exec jazzy --config jazzy.yaml
after_success:
  - bundle exec fastlane lib_push
  - bash <(curl -s https://codecov.io/bash)